---
kind: pipeline
type: exec
name: build

steps:
- name: pull
  commands:
    - git submodule init
    - git submodule update
    - cd cryptpad
    - git checkout $(git ls-remote -q --tags --refs --sort="committerdate" | tail -n1 | cut -d "/" -f3-)
    - cd ..
- name: build
  commands:
    - docker build -t gcrkrause/cryptpad:$(git submodule status | awk -F"[()]" '{print $2}') . --no-cache
