version: '2'
services:

  cryptpad:
    build:
      context: .
      args:
        - VERSION=${VERSION}
    image: "xwiki/cryptpad:${VERSION}"
    hostname: cryptpad

    labels:
      - traefik.port=3000
      - traefik.frontend.passHostHeader=true
    environment:
      - USE_SSL=${USE_SSL}
      - STORAGE=${STORAGE}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT}

    ports:
      - "3000:3000"
      - "3001:3001"

    restart: always
    volumes:
      - /var/storage/cryptpad/datastore:/cryptpad/datastore:rw
      - /var/storage/cryptpad/customize:/cryptpad/customize:rw
      - /var/storage/cryptpad/blob:/cryptpad/blob:rw
      - /var/storage/cryptpad/block:/cryptpad/block:rw
      - /var/storage/cryptpad/cfg:/cryptpad/cfg:rw
      - /var/storage/cryptpad/data:/cryptpad/data:rw
      - /var/storage/cryptpad/blobstage:/cryptpad/blobstage:rw
