---
version: '2'

services:
  cryptpad:
    labels:
      - traefik.http.routers.cryptpad.rule=Host(`cryptpad.example.com`)
      - traefik.http.routers.cryptpad-sandbox.rule=Host(`cryptpad-sandbox.example.com`)
      - traefik.http.routers.cryptpad.tls="true"
      - traefik.http.routers.cryptpad-sandbox.tls="true"
      - traefik.http.routers.cryptpad.entrypoints="https"
      - traefik.http.routers.cryptpad-sandbox.entrypoints="https"
      - traefik.http.services.cryptpad.loadbalancer.server.port=3000
      - traefik.http.services.cryptpad-sandbox.loadbalancer.server.port=3001